'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace myRageService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Branch", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Branch
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private branch_codeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private branch_nameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private address_line_1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private address_line_2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private address_line_3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private address_line_4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private address_line_5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private telephone_numberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private fax_numberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private email_addressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private pricelevelField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private tax_numberField As String
        
        Private is_blockedField As Boolean
        
        Private is_head_officeField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private branch_typeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private merchant_numberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private updatedField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private return_messageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private targetField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private longitudeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private latitudeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private tURLField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property branch_code() As String
            Get
                Return Me.branch_codeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.branch_codeField, value) <> true) Then
                    Me.branch_codeField = value
                    Me.RaisePropertyChanged("branch_code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property branch_name() As String
            Get
                Return Me.branch_nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.branch_nameField, value) <> true) Then
                    Me.branch_nameField = value
                    Me.RaisePropertyChanged("branch_name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property address_line_1() As String
            Get
                Return Me.address_line_1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.address_line_1Field, value) <> true) Then
                    Me.address_line_1Field = value
                    Me.RaisePropertyChanged("address_line_1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property address_line_2() As String
            Get
                Return Me.address_line_2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.address_line_2Field, value) <> true) Then
                    Me.address_line_2Field = value
                    Me.RaisePropertyChanged("address_line_2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property address_line_3() As String
            Get
                Return Me.address_line_3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.address_line_3Field, value) <> true) Then
                    Me.address_line_3Field = value
                    Me.RaisePropertyChanged("address_line_3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property address_line_4() As String
            Get
                Return Me.address_line_4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.address_line_4Field, value) <> true) Then
                    Me.address_line_4Field = value
                    Me.RaisePropertyChanged("address_line_4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property address_line_5() As String
            Get
                Return Me.address_line_5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.address_line_5Field, value) <> true) Then
                    Me.address_line_5Field = value
                    Me.RaisePropertyChanged("address_line_5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property telephone_number() As String
            Get
                Return Me.telephone_numberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.telephone_numberField, value) <> true) Then
                    Me.telephone_numberField = value
                    Me.RaisePropertyChanged("telephone_number")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property fax_number() As String
            Get
                Return Me.fax_numberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fax_numberField, value) <> true) Then
                    Me.fax_numberField = value
                    Me.RaisePropertyChanged("fax_number")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property email_address() As String
            Get
                Return Me.email_addressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.email_addressField, value) <> true) Then
                    Me.email_addressField = value
                    Me.RaisePropertyChanged("email_address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property pricelevel() As String
            Get
                Return Me.pricelevelField
            End Get
            Set
                If (Object.ReferenceEquals(Me.pricelevelField, value) <> true) Then
                    Me.pricelevelField = value
                    Me.RaisePropertyChanged("pricelevel")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property tax_number() As String
            Get
                Return Me.tax_numberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.tax_numberField, value) <> true) Then
                    Me.tax_numberField = value
                    Me.RaisePropertyChanged("tax_number")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=12)>  _
        Public Property is_blocked() As Boolean
            Get
                Return Me.is_blockedField
            End Get
            Set
                If (Me.is_blockedField.Equals(value) <> true) Then
                    Me.is_blockedField = value
                    Me.RaisePropertyChanged("is_blocked")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=13)>  _
        Public Property is_head_office() As Boolean
            Get
                Return Me.is_head_officeField
            End Get
            Set
                If (Me.is_head_officeField.Equals(value) <> true) Then
                    Me.is_head_officeField = value
                    Me.RaisePropertyChanged("is_head_office")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property branch_type() As String
            Get
                Return Me.branch_typeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.branch_typeField, value) <> true) Then
                    Me.branch_typeField = value
                    Me.RaisePropertyChanged("branch_type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Property merchant_number() As String
            Get
                Return Me.merchant_numberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.merchant_numberField, value) <> true) Then
                    Me.merchant_numberField = value
                    Me.RaisePropertyChanged("merchant_number")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=16)>  _
        Public Property updated() As String
            Get
                Return Me.updatedField
            End Get
            Set
                If (Object.ReferenceEquals(Me.updatedField, value) <> true) Then
                    Me.updatedField = value
                    Me.RaisePropertyChanged("updated")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=17)>  _
        Public Property return_message() As String
            Get
                Return Me.return_messageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.return_messageField, value) <> true) Then
                    Me.return_messageField = value
                    Me.RaisePropertyChanged("return_message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=18)>  _
        Public Property target() As String
            Get
                Return Me.targetField
            End Get
            Set
                If (Object.ReferenceEquals(Me.targetField, value) <> true) Then
                    Me.targetField = value
                    Me.RaisePropertyChanged("target")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=19)>  _
        Public Property longitude() As String
            Get
                Return Me.longitudeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.longitudeField, value) <> true) Then
                    Me.longitudeField = value
                    Me.RaisePropertyChanged("longitude")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=20)>  _
        Public Property latitude() As String
            Get
                Return Me.latitudeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.latitudeField, value) <> true) Then
                    Me.latitudeField = value
                    Me.RaisePropertyChanged("latitude")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=21)>  _
        Public Property tURL() As String
            Get
                Return Me.tURLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.tURLField, value) <> true) Then
                    Me.tURLField = value
                    Me.RaisePropertyChanged("tURL")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserPermissions", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UserPermissions
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private user_nameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private user_passwordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private branch_codeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private is_head_office_userField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private is_locked_to_branchField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private pos_sequenceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private maintenance_sequenceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private transaction_sequenceField As String
        
        Private isp27Field As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property user_name() As String
            Get
                Return Me.user_nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.user_nameField, value) <> true) Then
                    Me.user_nameField = value
                    Me.RaisePropertyChanged("user_name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property user_password() As String
            Get
                Return Me.user_passwordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.user_passwordField, value) <> true) Then
                    Me.user_passwordField = value
                    Me.RaisePropertyChanged("user_password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property branch_code() As String
            Get
                Return Me.branch_codeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.branch_codeField, value) <> true) Then
                    Me.branch_codeField = value
                    Me.RaisePropertyChanged("branch_code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property is_head_office_user() As String
            Get
                Return Me.is_head_office_userField
            End Get
            Set
                If (Object.ReferenceEquals(Me.is_head_office_userField, value) <> true) Then
                    Me.is_head_office_userField = value
                    Me.RaisePropertyChanged("is_head_office_user")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property is_locked_to_branch() As String
            Get
                Return Me.is_locked_to_branchField
            End Get
            Set
                If (Object.ReferenceEquals(Me.is_locked_to_branchField, value) <> true) Then
                    Me.is_locked_to_branchField = value
                    Me.RaisePropertyChanged("is_locked_to_branch")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property pos_sequence() As String
            Get
                Return Me.pos_sequenceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.pos_sequenceField, value) <> true) Then
                    Me.pos_sequenceField = value
                    Me.RaisePropertyChanged("pos_sequence")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property maintenance_sequence() As String
            Get
                Return Me.maintenance_sequenceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.maintenance_sequenceField, value) <> true) Then
                    Me.maintenance_sequenceField = value
                    Me.RaisePropertyChanged("maintenance_sequence")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property transaction_sequence() As String
            Get
                Return Me.transaction_sequenceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.transaction_sequenceField, value) <> true) Then
                    Me.transaction_sequenceField = value
                    Me.RaisePropertyChanged("transaction_sequence")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=8)>  _
        Public Property isp27() As Boolean
            Get
                Return Me.isp27Field
            End Get
            Set
                If (Me.isp27Field.Equals(value) <> true) Then
                    Me.isp27Field = value
                    Me.RaisePropertyChanged("isp27")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Stockcodes", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Stockcodes
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private generated_codeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private master_codeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private category_1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private category_2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private category_3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private sku_numberField As String
        
        Private is_service_itemField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private descriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private purchase_tax_groupField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private sales_tax_groupField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private supplierField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private suppliers_codeField As String
        
        Private is_not_discountableField As Boolean
        
        Private is_blockedField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private minimum_stock_levelField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private item_sizeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private item_colourField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private size_matrixField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private colour_matrixField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private cost_priceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private estimated_costField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private selling_price_1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private selling_price_2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private selling_price_3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private updatedField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private createdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private qty_on_handField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property generated_code() As String
            Get
                Return Me.generated_codeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.generated_codeField, value) <> true) Then
                    Me.generated_codeField = value
                    Me.RaisePropertyChanged("generated_code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property master_code() As String
            Get
                Return Me.master_codeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.master_codeField, value) <> true) Then
                    Me.master_codeField = value
                    Me.RaisePropertyChanged("master_code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property category_1() As String
            Get
                Return Me.category_1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.category_1Field, value) <> true) Then
                    Me.category_1Field = value
                    Me.RaisePropertyChanged("category_1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property category_2() As String
            Get
                Return Me.category_2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.category_2Field, value) <> true) Then
                    Me.category_2Field = value
                    Me.RaisePropertyChanged("category_2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property category_3() As String
            Get
                Return Me.category_3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.category_3Field, value) <> true) Then
                    Me.category_3Field = value
                    Me.RaisePropertyChanged("category_3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property sku_number() As String
            Get
                Return Me.sku_numberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.sku_numberField, value) <> true) Then
                    Me.sku_numberField = value
                    Me.RaisePropertyChanged("sku_number")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property is_service_item() As Boolean
            Get
                Return Me.is_service_itemField
            End Get
            Set
                If (Me.is_service_itemField.Equals(value) <> true) Then
                    Me.is_service_itemField = value
                    Me.RaisePropertyChanged("is_service_item")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.descriptionField, value) <> true) Then
                    Me.descriptionField = value
                    Me.RaisePropertyChanged("description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property purchase_tax_group() As String
            Get
                Return Me.purchase_tax_groupField
            End Get
            Set
                If (Object.ReferenceEquals(Me.purchase_tax_groupField, value) <> true) Then
                    Me.purchase_tax_groupField = value
                    Me.RaisePropertyChanged("purchase_tax_group")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property sales_tax_group() As String
            Get
                Return Me.sales_tax_groupField
            End Get
            Set
                If (Object.ReferenceEquals(Me.sales_tax_groupField, value) <> true) Then
                    Me.sales_tax_groupField = value
                    Me.RaisePropertyChanged("sales_tax_group")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property supplier() As String
            Get
                Return Me.supplierField
            End Get
            Set
                If (Object.ReferenceEquals(Me.supplierField, value) <> true) Then
                    Me.supplierField = value
                    Me.RaisePropertyChanged("supplier")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property suppliers_code() As String
            Get
                Return Me.suppliers_codeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.suppliers_codeField, value) <> true) Then
                    Me.suppliers_codeField = value
                    Me.RaisePropertyChanged("suppliers_code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=12)>  _
        Public Property is_not_discountable() As Boolean
            Get
                Return Me.is_not_discountableField
            End Get
            Set
                If (Me.is_not_discountableField.Equals(value) <> true) Then
                    Me.is_not_discountableField = value
                    Me.RaisePropertyChanged("is_not_discountable")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=13)>  _
        Public Property is_blocked() As Boolean
            Get
                Return Me.is_blockedField
            End Get
            Set
                If (Me.is_blockedField.Equals(value) <> true) Then
                    Me.is_blockedField = value
                    Me.RaisePropertyChanged("is_blocked")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property minimum_stock_level() As String
            Get
                Return Me.minimum_stock_levelField
            End Get
            Set
                If (Object.ReferenceEquals(Me.minimum_stock_levelField, value) <> true) Then
                    Me.minimum_stock_levelField = value
                    Me.RaisePropertyChanged("minimum_stock_level")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Property item_size() As String
            Get
                Return Me.item_sizeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.item_sizeField, value) <> true) Then
                    Me.item_sizeField = value
                    Me.RaisePropertyChanged("item_size")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=16)>  _
        Public Property item_colour() As String
            Get
                Return Me.item_colourField
            End Get
            Set
                If (Object.ReferenceEquals(Me.item_colourField, value) <> true) Then
                    Me.item_colourField = value
                    Me.RaisePropertyChanged("item_colour")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=17)>  _
        Public Property size_matrix() As String
            Get
                Return Me.size_matrixField
            End Get
            Set
                If (Object.ReferenceEquals(Me.size_matrixField, value) <> true) Then
                    Me.size_matrixField = value
                    Me.RaisePropertyChanged("size_matrix")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=18)>  _
        Public Property colour_matrix() As String
            Get
                Return Me.colour_matrixField
            End Get
            Set
                If (Object.ReferenceEquals(Me.colour_matrixField, value) <> true) Then
                    Me.colour_matrixField = value
                    Me.RaisePropertyChanged("colour_matrix")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=19)>  _
        Public Property cost_price() As String
            Get
                Return Me.cost_priceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cost_priceField, value) <> true) Then
                    Me.cost_priceField = value
                    Me.RaisePropertyChanged("cost_price")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=20)>  _
        Public Property estimated_cost() As String
            Get
                Return Me.estimated_costField
            End Get
            Set
                If (Object.ReferenceEquals(Me.estimated_costField, value) <> true) Then
                    Me.estimated_costField = value
                    Me.RaisePropertyChanged("estimated_cost")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=21)>  _
        Public Property selling_price_1() As String
            Get
                Return Me.selling_price_1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.selling_price_1Field, value) <> true) Then
                    Me.selling_price_1Field = value
                    Me.RaisePropertyChanged("selling_price_1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=22)>  _
        Public Property selling_price_2() As String
            Get
                Return Me.selling_price_2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.selling_price_2Field, value) <> true) Then
                    Me.selling_price_2Field = value
                    Me.RaisePropertyChanged("selling_price_2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=23)>  _
        Public Property selling_price_3() As String
            Get
                Return Me.selling_price_3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.selling_price_3Field, value) <> true) Then
                    Me.selling_price_3Field = value
                    Me.RaisePropertyChanged("selling_price_3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=24)>  _
        Public Property updated() As String
            Get
                Return Me.updatedField
            End Get
            Set
                If (Object.ReferenceEquals(Me.updatedField, value) <> true) Then
                    Me.updatedField = value
                    Me.RaisePropertyChanged("updated")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=25)>  _
        Public Property created() As String
            Get
                Return Me.createdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.createdField, value) <> true) Then
                    Me.createdField = value
                    Me.RaisePropertyChanged("created")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=26)>  _
        Public Property qty_on_hand() As String
            Get
                Return Me.qty_on_handField
            End Get
            Set
                If (Object.ReferenceEquals(Me.qty_on_handField, value) <> true) Then
                    Me.qty_on_handField = value
                    Me.RaisePropertyChanged("qty_on_hand")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="myRageService.testingSoap")>  _
    Public Interface testingSoap
        
        'CODEGEN: Generating message contract since element name Password from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetBranches", ReplyAction:="*")>  _
        Function GetBranches(ByVal request As myRageService.GetBranchesRequest) As myRageService.GetBranchesResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetBranches", ReplyAction:="*")>  _
        Function GetBranchesAsync(ByVal request As myRageService.GetBranchesRequest) As System.Threading.Tasks.Task(Of myRageService.GetBranchesResponse)
        
        'CODEGEN: Generating message contract since element name Password from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetUsersTesting", ReplyAction:="*")>  _
        Function GetUsersTesting(ByVal request As myRageService.GetUsersTestingRequest) As myRageService.GetUsersTestingResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetUsersTesting", ReplyAction:="*")>  _
        Function GetUsersTestingAsync(ByVal request As myRageService.GetUsersTestingRequest) As System.Threading.Tasks.Task(Of myRageService.GetUsersTestingResponse)
        
        'CODEGEN: Generating message contract since element name GetSomeStockcodesTestingResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSomeStockcodesTesting", ReplyAction:="*")>  _
        Function GetSomeStockcodesTesting(ByVal request As myRageService.GetSomeStockcodesTestingRequest) As myRageService.GetSomeStockcodesTestingResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSomeStockcodesTesting", ReplyAction:="*")>  _
        Function GetSomeStockcodesTestingAsync(ByVal request As myRageService.GetSomeStockcodesTestingRequest) As System.Threading.Tasks.Task(Of myRageService.GetSomeStockcodesTestingResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetBranchesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetBranches", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As myRageService.GetBranchesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As myRageService.GetBranchesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetBranchesRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Database As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public BranchCode As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Password As String, ByVal Database As String, ByVal BranchCode As String)
            MyBase.New
            Me.Password = Password
            Me.Database = Database
            Me.BranchCode = BranchCode
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetBranchesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetBranchesResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As myRageService.GetBranchesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As myRageService.GetBranchesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetBranchesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetBranchesResult() As myRageService.Branch
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetBranchesResult() As myRageService.Branch)
            MyBase.New
            Me.GetBranchesResult = GetBranchesResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUsersTestingRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUsersTesting", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As myRageService.GetUsersTestingRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As myRageService.GetUsersTestingRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetUsersTestingRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Database As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public BranchCode As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Password As String, ByVal Database As String, ByVal BranchCode As String)
            MyBase.New
            Me.Password = Password
            Me.Database = Database
            Me.BranchCode = BranchCode
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUsersTestingResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUsersTestingResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As myRageService.GetUsersTestingResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As myRageService.GetUsersTestingResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetUsersTestingResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetUsersTestingResult() As myRageService.UserPermissions
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUsersTestingResult() As myRageService.UserPermissions)
            MyBase.New
            Me.GetUsersTestingResult = GetUsersTestingResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetSomeStockcodesTestingRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetSomeStockcodesTesting", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As myRageService.GetSomeStockcodesTestingRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As myRageService.GetSomeStockcodesTestingRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetSomeStockcodesTestingRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetSomeStockcodesTestingResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetSomeStockcodesTestingResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As myRageService.GetSomeStockcodesTestingResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As myRageService.GetSomeStockcodesTestingResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetSomeStockcodesTestingResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetSomeStockcodesTestingResult() As myRageService.Stockcodes
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetSomeStockcodesTestingResult() As myRageService.Stockcodes)
            MyBase.New
            Me.GetSomeStockcodesTestingResult = GetSomeStockcodesTestingResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface testingSoapChannel
        Inherits myRageService.testingSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class testingSoapClient
        Inherits System.ServiceModel.ClientBase(Of myRageService.testingSoap)
        Implements myRageService.testingSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function myRageService_testingSoap_GetBranches(ByVal request As myRageService.GetBranchesRequest) As myRageService.GetBranchesResponse Implements myRageService.testingSoap.GetBranches
            Return MyBase.Channel.GetBranches(request)
        End Function
        
        Public Function GetBranches(ByVal Password As String, ByVal Database As String, ByVal BranchCode As String) As myRageService.Branch()
            Dim inValue As myRageService.GetBranchesRequest = New myRageService.GetBranchesRequest()
            inValue.Body = New myRageService.GetBranchesRequestBody()
            inValue.Body.Password = Password
            inValue.Body.Database = Database
            inValue.Body.BranchCode = BranchCode
            Dim retVal As myRageService.GetBranchesResponse = CType(Me,myRageService.testingSoap).GetBranches(inValue)
            Return retVal.Body.GetBranchesResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function myRageService_testingSoap_GetBranchesAsync(ByVal request As myRageService.GetBranchesRequest) As System.Threading.Tasks.Task(Of myRageService.GetBranchesResponse) Implements myRageService.testingSoap.GetBranchesAsync
            Return MyBase.Channel.GetBranchesAsync(request)
        End Function
        
        Public Function GetBranchesAsync(ByVal Password As String, ByVal Database As String, ByVal BranchCode As String) As System.Threading.Tasks.Task(Of myRageService.GetBranchesResponse)
            Dim inValue As myRageService.GetBranchesRequest = New myRageService.GetBranchesRequest()
            inValue.Body = New myRageService.GetBranchesRequestBody()
            inValue.Body.Password = Password
            inValue.Body.Database = Database
            inValue.Body.BranchCode = BranchCode
            Return CType(Me,myRageService.testingSoap).GetBranchesAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function myRageService_testingSoap_GetUsersTesting(ByVal request As myRageService.GetUsersTestingRequest) As myRageService.GetUsersTestingResponse Implements myRageService.testingSoap.GetUsersTesting
            Return MyBase.Channel.GetUsersTesting(request)
        End Function
        
        Public Function GetUsersTesting(ByVal Password As String, ByVal Database As String, ByVal BranchCode As String) As myRageService.UserPermissions()
            Dim inValue As myRageService.GetUsersTestingRequest = New myRageService.GetUsersTestingRequest()
            inValue.Body = New myRageService.GetUsersTestingRequestBody()
            inValue.Body.Password = Password
            inValue.Body.Database = Database
            inValue.Body.BranchCode = BranchCode
            Dim retVal As myRageService.GetUsersTestingResponse = CType(Me,myRageService.testingSoap).GetUsersTesting(inValue)
            Return retVal.Body.GetUsersTestingResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function myRageService_testingSoap_GetUsersTestingAsync(ByVal request As myRageService.GetUsersTestingRequest) As System.Threading.Tasks.Task(Of myRageService.GetUsersTestingResponse) Implements myRageService.testingSoap.GetUsersTestingAsync
            Return MyBase.Channel.GetUsersTestingAsync(request)
        End Function
        
        Public Function GetUsersTestingAsync(ByVal Password As String, ByVal Database As String, ByVal BranchCode As String) As System.Threading.Tasks.Task(Of myRageService.GetUsersTestingResponse)
            Dim inValue As myRageService.GetUsersTestingRequest = New myRageService.GetUsersTestingRequest()
            inValue.Body = New myRageService.GetUsersTestingRequestBody()
            inValue.Body.Password = Password
            inValue.Body.Database = Database
            inValue.Body.BranchCode = BranchCode
            Return CType(Me,myRageService.testingSoap).GetUsersTestingAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function myRageService_testingSoap_GetSomeStockcodesTesting(ByVal request As myRageService.GetSomeStockcodesTestingRequest) As myRageService.GetSomeStockcodesTestingResponse Implements myRageService.testingSoap.GetSomeStockcodesTesting
            Return MyBase.Channel.GetSomeStockcodesTesting(request)
        End Function
        
        Public Function GetSomeStockcodesTesting() As myRageService.Stockcodes()
            Dim inValue As myRageService.GetSomeStockcodesTestingRequest = New myRageService.GetSomeStockcodesTestingRequest()
            inValue.Body = New myRageService.GetSomeStockcodesTestingRequestBody()
            Dim retVal As myRageService.GetSomeStockcodesTestingResponse = CType(Me,myRageService.testingSoap).GetSomeStockcodesTesting(inValue)
            Return retVal.Body.GetSomeStockcodesTestingResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function myRageService_testingSoap_GetSomeStockcodesTestingAsync(ByVal request As myRageService.GetSomeStockcodesTestingRequest) As System.Threading.Tasks.Task(Of myRageService.GetSomeStockcodesTestingResponse) Implements myRageService.testingSoap.GetSomeStockcodesTestingAsync
            Return MyBase.Channel.GetSomeStockcodesTestingAsync(request)
        End Function
        
        Public Function GetSomeStockcodesTestingAsync() As System.Threading.Tasks.Task(Of myRageService.GetSomeStockcodesTestingResponse)
            Dim inValue As myRageService.GetSomeStockcodesTestingRequest = New myRageService.GetSomeStockcodesTestingRequest()
            inValue.Body = New myRageService.GetSomeStockcodesTestingRequestBody()
            Return CType(Me,myRageService.testingSoap).GetSomeStockcodesTestingAsync(inValue)
        End Function
    End Class
End Namespace
